version: '3.7'
services:
  db: #Database (PostgreSQL)
    build: #Indicate to build with Dockerfile present in ./postgreSQL folder
      context: ./postgresSQL
      dockerfile: Dockerfile 
    restart: always #If Database crash 
    environment:
       POSTGRES_HOST_AUTH_METHOD: 'trust'
       POSTGRES_PASSWORD: 'root'
       POSTGRES_DB: 'postgres'    
    ports:
      # Open port 5432 of container 
      - '5432:5432'
    volumes: #Volume to persist data
      - database:/var/lib/postgresql/data
  payara:
    depends_on: #Wait for DB to be up before lauchning identify by "db"
      - db
    links: #Link docker together instead of "use network"
      - db
    build: #Indicate to build with Dockerfile present in ./payara
        context: ./payara
        dockerfile: Dockerfile
    restart: always
    ports:
      #port exposed
      - '8080:8080' #Access to application load on server
      - '4848:4848' #Access to admin dashboard
    volumes: #Volume to persist log data
      - payara:/opt/payara/appserver/glassfish/domains/production/logs
volumes: #Create volume at docker-compose up
   database:
   payara:
